### ISSUE TITLE
Cannot create a typescript valid nesting group

### ISSUE THREAD

**Issue by tomasfrancisco** [terrazzoapp/terrazzo#338]
I've been trying to find a good way to nest groups using `@terrazzo/tokens-tools`, but typescript (v5.6.3) seems to not be happy with it. 

[Reproduction @ CodeSandbox](https://codesandbox.io/p/sandbox/pyt65w)

![Screenshot 2024-11-07 at 16 15 19](https://github.com/user-attachments/assets/41c038fe-6bbd-4378-8419-ed0f54cefb3c)

Here are some references I've came across:
1. https://stackoverflow.com/questions/59896317/typescript-key-index-signature-only-for-all-properties-that-are-not-defined
1. https://github.com/microsoft/TypeScript/issues/17867

One workaround that could possible be used here is the repetition of type `GroupCore` in the inner properties and as an isolated union element of type `Group`.

**Before:**
```ts
export type Group = GroupCore & {
    [key: string]: GroupOrToken;
};
```

**Workaround:**
```ts
export type Group = GroupCore & {
    [key: string]: GroupOrToken | GroupCore;
} | GroupCore;
```

Or is there something I'm missing here?

**Comment by drwpow** [comment]
Ah you’re right this may be an impossible intersection. I actually think we could just have `GroupCore | { [key: string]: GroupOrToken | GroupCore }` to simplify it, since unions in TypeScript aren’t exclusive. But if that doesn’t work, your fix is good!

This typing is more for internal usage, but complexity like this are why typing the DTCG spec with JSONSchema is tricky!
